### ISSUE TITLE
Thoughts on working around a potential chromium import map bug?

### ISSUE THREAD

**Issue by lewisl9029** [guybedford/es-module-shims#282] opened 2022-04-05 03:13 UTC
Hi there!

I've been exploring using modulepreload links as an optimization and ran into what I believe is a bug in Chromium's import map implementation: https://bugs.chromium.org/p/chromium/issues/detail?id=1313317

Gist of the issue is import maps seem to be ignored when scripts are loaded from memory cache, causing the import to fail. Repro steps can be found in the linked issue.

The symptom in this case is similar to a browser without importmap support, where an error like the following will be logged:
> Uncaught TypeError: Failed to resolve module specifier "react". Relative references must start with either "/", "./", or "../".

This led me to wonder if it could be possible to use es-module-shims to detect and work around this issue somehow, possibly by exposing some function to call to manually initialize the polyfill based on some custom detection code, if not automatically out-of-the-box. 

If valid, this bug could have existed for quite a few stable chromium versions, and might not get fixed for quite a few more, so seems worthwhile for the polyfill to take into account.

Curious to hear if you think this could be a worthwhile addition. If so, I'd be happy to take a crack at it!

Thanks!

**Comment by guybedford** [comment] 2022-04-05 13:02
@lewisl9029 I think the issue here is that you need to put the `<modulepreload>` tags _after_ the import map as otherwise they will error and cache that error in the module loader when imported later. I'd suggest posting an issue to the whatwg/html or import maps repo about this scenario to try and clear up if it is a bug or not.

The outcome of what ES Module Shims should do here exactly depends on whether the behaviour is by design or something that needs to be fixed, respecified etc.

**Comment by lewisl9029** [comment] 2022-04-05 16:57
Hmm a few reasons on why this still feels like a bug to me:

- It only errors when loaded from memory cache, not disk cache, nor when there's no cache.
- From my understanding, preloaded modules supposed to be inert and only executed once actually imported using the script tag, so positioning shouldn't affect behavior?

But yes posting to the import maps repo to get more eyes on it does seem like a good idea. I'll go ahead and do that!

**Comment by lewisl9029** [comment] 2022-04-05 17:07
I forgot to mention that originally, I was trying to use the modulepreload _header_, and ended up seeing this exact issue, so now I'm trying to backtrack and isolate the issue.

As you could imagine, modulepreload as a _header_ would become pretty untenable if this is intended behavior when import maps are specified.

**Comment by guybedford** [comment] 2022-05-15 02:12
Closing, as the chrome bug has been resolved now.

**Closed by guybedford** 2022-05-15 02:12 UTC
