### ISSUE TITLE
Minified imports give an error

### ISSUE THREAD

**Issue by alber70g** [guybedford/es-module-shims#10] opened 2019-03-28 12:48 UTC
When using a minified file it doesn't split the import line on `;`

Eg:

Unminified works fine:
```js
import x from 'y';
import z from 'a';
console.log(x)
```

Minified is broken. We get the error `Error: Unable to resolve bare specifier ";console.log(x)`
```js
import x from 'y';import z from 'a';console.log(x)
```

It seems that it doesn't parse the code and splits statements on `;`

**Comment by guybedford** [comment] 2019-03-28 13:05
Thanks so much for posting, always happy to fix parser bugs.

The example you shared doesn't seem to replicate for me here though unfortunately (I get `Unable to resolve bare specifier 'a'` just fine).

Is there code before the `import x from 'y'` line? That may well be the cause of getting into an invalid state earlier.

**Comment by alber70g** [comment] 2019-03-28 13:23
I think I've oversimplified the example. We have a somewhat more complex example.

The actual error is:

`Error: Unable to resolve bare specifier ";window.JSCompiler_renameProperty=((t,e)=>t);const s={toAttribute(t,e){switch(e){case Boolean:return t?" from http://localhost:3000/dist/module/vendor/lit-element.js`
 
What actually happens is the following:

1. we load index with the es-module-shims and the imports map and module-shim

```html
    <script type="importmap-shim">
      {
        "imports": {
          
          "lit-html": "./dist/module/vendor/lit-html.js",
          "lit-html/lit-html": "./dist/module/vendor/lit-html.js",
          "lit-html/directives/repeat": "./dist/module/vendor/lit-html.js",
          "lit-html/lib/shady-render": "./dist/module/vendor/lit-html.js",
          "lit-element": "./dist/module/vendor/lit-element.js"
        }
      }
    </script>
    <script type="module-shim">
      import("./dist/module/ing-owc/0.0.0/main.js");
      window.supportsDynamicImport = true;
    </script>
```


2. Then inside the main.js we dynamically load some other sources `layout.js` which in turn load `lit-html` and `lit-element`

3. the `lit-element.js` contains this line which is causing issues:

`import{TemplateResult as t}from"lit-html";import{a as e}from"./chunk-4be41b30.js";export{j as SVGTemplateResult,i as TemplateResult,g as html,h as svg}from"./chunk-4be41b30.js";window.JSCompiler_renameProperty=( ............`


Does this provide the necessary context?

**Comment by guybedford** [comment] 2019-03-28 13:46
Perfect, yes that got it down. I've posted a fix in https://github.com/guybedford/es-module-shims/commit/5139679919662da444127412dfc12d27b9ba6dbc and released in 0.2.2.

**Comment by alber70g** [comment] 2019-03-28 13:46
Nice! You're awesome!

**Closed by guybedford** 2019-03-28 13:46 UTC

**Comment by alber70g** [comment] 2019-03-29 11:31
Just a heads-up, I think you didn't release the minified version of 0.2.2. It's still `/* ES Module Shims 0.2.1 */`

**Comment by guybedford** [comment] 2019-03-29 21:24
@alber70g thanks for letting me know, I've pushed up a 0.2.3.
