### ISSUE TITLE
different script order in Safari seems to break JS

### ISSUE THREAD

**Issue by itsyoshio** [guybedford/es-module-shims#285] opened 2022-04-26 20:58 UTC
i'm having an issue in Safari explicitly, where JS works on the first (uncached) pageload.
Afterwards it just stops working.

Each time i change something in the page and make the browser reload it, it does work again (figure 1), each subsequent load (figure 2) will result in some Stimulus Controllers to break

<figure>
<img src="https://user-images.githubusercontent.com/12760988/165390563-d5401715-8485-4589-b4b8-9e85b146a37a.png" alt="Trulli" style="width:100%">
<figcaption align = "center"><b>Fig.1 Working - shim before controllers</b></figcaption>
</figure>

---

<figure>
<img src="https://user-images.githubusercontent.com/12760988/165390534-1e3a84d4-ae52-4a82-afde-ecc1bfa07ddf.png" alt="Trulli" style="width:100%">
<figcaption align = "center"><b>Fig.2 not Working - shim after controllers</b></figcaption>
</figure>

any and all help is appreciated :)

**Comment by guybedford** [comment] 2022-05-02 00:14
Is the `/application.js` executing at all if you add a log into it? That would be the first thing to check.

Depending on whether it is or not, it will either be a polyfill issue or a load event issue (https://github.com/guybedford/es-module-shims#no-load-event-retriggers).

**Comment by guybedford** [comment] 2022-05-11 17:40
Marking this as a duplicate of https://github.com/guybedford/es-module-shims/issues/285 and moving discussion there given that issue has a replication. If it turns out this isn't captured by that issue, we can always reopen.

**Closed by guybedford** 2022-05-11 17:40 UTC
